### ISSUE TITLE
I would like autofix for the regular nesting, but not for @nest

### ISSUE THREAD

**Issue by martijndevalk** [csstools/stylelint-prefer-nesting#10]
Hi,

When using the setting "codeActionsOnSave" in VS Code in combination with the following CSS:

```css
.transition > .list {
  margin: 0;
}

.list {
  background-color: pink;
}
```

I would expect the rule to behave like this:

```css
.transition {
  & > .list {
    margin: 0;
  }
}

.list {
  background-color: pink;
}
```

Instead, this happens: 

```css
.list {
  background-color: pink;

  @nest .transition > & {
    margin: 0;
  }
}
```

Would it be possible to make the autofix `@nest` configurable or just disable it would help? 

Thanks!
