### ISSUE TITLE
Unknown rule csstools/use-nesting

### ISSUE THREAD

**Issue by netsvetoch** [csstools/stylelint-prefer-nesting#19]
My ```.stylelintrc.yaml```:
```
extends:
  - stylelint-config-standard
  - stylelint-config-recess-order
  - stylelint-use-nesting
rules:
  color-function-notation: modern
  selector-class-pattern: null
  csstools/use-nesting: always
```

The ```npx  stylelint "**/*.css"``` command always reports ```Unknown rule csstools/use-nesting``` problem. How to fix it?
